module.exports = {
  purge: [],
  theme: {
    extend: {
      colors: {
        'black': 'var(--color-black)',
        'white': 'var(--color-white)',
        gray: {
          100: 'var(--color-gray-100)',
          200: 'var(--color-gray-200)',
          300: 'var(--color-gray-300)',
          400: 'var(--color-gray-400)',
          500: 'var(--color-gray-500)',
          600: 'var(--color-gray-600)',
          700: 'var(--color-gray-700)',
          800: 'var(--color-gray-800)',
          900: 'var(--color-gray-900)',
        },
        red: {
          100: 'var(--color-red-100)',
          200: 'var(--color-red-200)',
          300: 'var(--color-red-300)',
          400: 'var(--color-red-400)',
          500: 'var(--color-red-500)',
          600: 'var(--color-red-600)',
          700: 'var(--color-red-700)',
          800: 'var(--color-red-800)',
          900: 'var(--color-red-900)',
        },
        orange: {
          100: 'var(--color-orange-100)',
          200: 'var(--color-orange-200)',
          300: 'var(--color-orange-300)',
          400: 'var(--color-orange-400)',
          500: 'var(--color-orange-500)',
          600: 'var(--color-orange-600)',
          700: 'var(--color-orange-700)',
          800: 'var(--color-orange-800)',
          900: 'var(--color-orange-900)',
        },
        yellow: {
          100: 'var(--color-yellow-100)',
          200: 'var(--color-yellow-200)',
          300: 'var(--color-yellow-300)',
          400: 'var(--color-yellow-400)',
          500: 'var(--color-yellow-500)',
          600: 'var(--color-yellow-600)',
          700: 'var(--color-yellow-700)',
          800: 'var(--color-yellow-800)',
          900: 'var(--color-yellow-900)',
        },
        green: {
          100: 'var(--color-green-100)',
          200: 'var(--color-green-200)',
          300: 'var(--color-green-300)',
          400: 'var(--color-green-400)',
          500: 'var(--color-green-500)',
          600: 'var(--color-green-600)',
          700: 'var(--color-green-700)',
          800: 'var(--color-green-800)',
          900: 'var(--color-green-900)',
        },
        teal: {
          100: 'var(--color-teal-100)',
          200: 'var(--color-teal-200)',
          300: 'var(--color-teal-300)',
          400: 'var(--color-teal-400)',
          500: 'var(--color-teal-500)',
          600: 'var(--color-teal-600)',
          700: 'var(--color-teal-700)',
          800: 'var(--color-teal-800)',
          900: 'var(--color-teal-900)',
        },
        blue: {
          100: 'var(--color-blue-100)',
          200: 'var(--color-blue-200)',
          300: 'var(--color-blue-300)',
          400: 'var(--color-blue-400)',
          500: 'var(--color-blue-500)',
          600: 'var(--color-blue-600)',
          700: 'var(--color-blue-700)',
          800: 'var(--color-blue-800)',
          900: 'var(--color-blue-900)',
        },
        indigo: {
          100: 'var(--color-indigo-100)',
          200: 'var(--color-indigo-200)',
          300: 'var(--color-indigo-300)',
          400: 'var(--color-indigo-400)',
          500: 'var(--color-indigo-500)',
          600: 'var(--color-indigo-600)',
          700: 'var(--color-indigo-700)',
          800: 'var(--color-indigo-800)',
          900: 'var(--color-indigo-900)',
        },
        purple: {
          100: 'var(--color-purple-100)',
          200: 'var(--color-purple-200)',
          300: 'var(--color-purple-300)',
          400: 'var(--color-purple-400)',
          500: 'var(--color-purple-500)',
          600: 'var(--color-purple-600)',
          700: 'var(--color-purple-700)',
          800: 'var(--color-purple-800)',
          900: 'var(--color-purple-900)',
        },
        pink: {
          100: 'var(--color-pink-100)',
          200: 'var(--color-pink-200)',
          300: 'var(--color-pink-300)',
          400: 'var(--color-pink-400)',
          500: 'var(--color-pink-500)',
          600: 'var(--color-pink-600)',
          700: 'var(--color-pink-700)',
          800: 'var(--color-pink-800)',
          900: 'var(--color-pink-900)',
        },
      },
      // ...
    },
  },
  variants: {},
  plugins: [],
  corePlugins: {
    // preflight: false,
    // container: false,
    // accessibility: false,
    // alignContent: false,
    // alignItems: false,
    // alignSelf: false,
     animation: false,
    // appearance: false,
    // backgroundAttachment: false,
    // backgroundClip: false,
    // backgroundColor: false,
    // backgroundImage: false,
     backgroundOpacity: false,
    // backgroundPosition: false,
    // backgroundRepeat: false,
    // backgroundSize: false,
    // borderCollapse: false,
    // borderColor: false,
     borderOpacity: false,
    // borderRadius: false,
    // borderStyle: false,
    // borderWidth: false,
    // boxShadow: false,
    // boxSizing: false,
    // clear: false,
    // cursor: false,
    // display: false,
     divideColor: false,
     divideOpacity: false,
     divideStyle: false,
     divideWidth: false,
    // fill: false,
    // flex: false,
    // flexDirection: false,
    // flexGrow: false,
    // flexShrink: false,
    // flexWrap: false,
    // float: false,
    // fontFamily: false,
    // fontSize: false,
    // fontSmoothing: false,
    // fontStyle: false,
    // fontWeight: false,
     gap: false,
     gradientColorStops: false,
     gridAutoFlow: false,
     gridColumn: false,
     gridColumnEnd: false,
     gridColumnStart: false,
     gridRow: false,
     gridRowEnd: false,
     gridRowStart: false,
     gridTemplateColumns: false,
     gridTemplateRows: false,
    // height: false,
    // inset: false,
    // justifyContent: false,
    // letterSpacing: false,
    // lineHeight: false,
    // listStylePosition: false,
    // listStyleType: false,
    // margin: false,
    // maxHeight: false,
    // maxWidth: false,
    // minHeight: false,
    // minWidth: false,
     objectFit: false,
     objectPosition: false,
    // opacity: false,
    // order: false,
    // outline: false,
    // overflow: false,
    // overscrollBehavior: false,
    // padding: false,
    // placeholderColor: false,
    // placeholderOpacity: false,
    // pointerEvents: false,
    // position: false,
    // resize: false,
    // rotate: false,
    // scale: false,
    // skew: false,
    // space: false,
    // stroke: false,
     strokeWidth: false,
    // tableLayout: false,
    // textAlign: false,
    // textColor: false,
    // textDecoration: false,
     textOpacity: false,
    // textTransform: false,
    // transform: false,
    // transformOrigin: false,
    // transitionDelay: false,
    // transitionDuration: false,
    // transitionProperty: false,
    // transitionTimingFunction: false,
    // translate: false,
    // userSelect: false,
    // verticalAlign: false,
    // visibility: false,
    // whitespace: false,
    // width: false,
    // wordBreak: false,
    // zIndex: false,
  },
  future: {
    removeDeprecatedGapUtilities: true,
  },
}